MODULE ENV
    
USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT16, INT32, INT64, &
                                        REAL32, REAL64, REAL128
USE ISO_C_BINDING, ONLY: C_DOUBLE, C_FLOAT

IMPLICIT NONE

PRIVATE

INTEGER, PARAMETER, PUBLIC :: WINT = INT32
INTEGER, PARAMETER, PUBLIC :: WREAL = REAL64
INTEGER, PARAMETER, PUBLIC :: C_REAL = C_DOUBLE

END MODULE ENV